spring:
  application:
    name: buyit
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?TimeZone=Asia/Kolkata
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true
  redis:
    host: localhost
    port: 6379
    timeout: 60000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hour in milliseconds
server:
  port: 8080

